# Generated by Django 5.0.3 on 2024-04-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="age_WRP",
            field=models.CharField(
                choices=[
                    ("FPJ", "(FPJ) First prejuvenile molt"),
                    ("FCJ", "(FCJ) First cycle juvenile plumage"),
                    ("FPF", "(FPF) First preformative molt"),
                    ("FCF", "(FCF) First cycle formative plumage"),
                    ("MFCF", "(M-FCF) Minimum first cycle formative"),
                    ("FPA", "(FPA) First prealternate molt"),
                    ("MFPA", "(M-FPA) Minimum first cycle prealternate"),
                    ("FCA", "(FCA) First cycle alternate plumage"),
                    ("MFCA", "(M-FCA) Minimum first cycle alternate"),
                    ("SPB", "(SPB) Second prebasic molt"),
                    ("MSPB", "(M-SPB) Minimum second prebasic molt"),
                    ("SCB", "(SCB) Second cycle basic plumage"),
                    ("DPB", "(DPB) Definitive prebasic molt"),
                    ("DCB", "(DCB) Definitive cycle basic plumage"),
                    ("DPA", "(DPA) Definitive prealternate molt"),
                    ("DCA", "(DCA) Definitive cycle alternate plumage"),
                    ("TPB", "(TPB) Third prebasic molt"),
                    ("FCU", "(FCU) First cycle unknown plumage"),
                    ("DCU", "(DCU) Definitive cycle unknown plumage"),
                    ("UCU", "(UCU) Unknown cycle unknown plumage"),
                ],
                default="MFCF",
                max_length=4,
            ),
        ),
    ]
