# Generated by Django 5.0.3 on 2024-03-09 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="species_number",
            field=models.IntegerField(
                choices=[
                    (5810, "SOSP - Song Sparrow"),
                    (6460, "OCWA - Orange-crowned Warbler"),
                    (5880, "SPTO - Spotted Towhee"),
                    (7580, "SWTH - Swainson's Thrush"),
                    (4310, "ANHU - Anna's Hummingbird"),
                    (3160, "MODO - Mourning Dove"),
                    (4240, "VASW - Vaux's Swift"),
                    (4330, "RUHU - Rufous Hummingbird"),
                    (2120, "VIRA - Virginia Rail"),
                    (3320, "SSHA - Sharp-shinned Hawk"),
                    (3330, "COHA - Cooper's Hawk"),
                    (3650, "BNOW - Barn Owl"),
                    (3750, "GHOW - Great Horned Owl"),
                    (3900, "BEKI - Belted Kingfisher"),
                    (4030, "RBSA - Red-breasted Sapsucker"),
                    (3940, "DOWO - Downy Woodpecker"),
                    (3930, "HAWO - Hairy Woodpecker"),
                    (4130, "RSFL - Red-shafted Flicker"),
                    (4050, "PIWO - Pileated Woodpecker"),
                    (4590, "OSFL - Olive-sided Flycatcher"),
                    (4620, "WEWP - Western Wood-Pewee"),
                    (4660, "WIFL - Willow Flycatcher"),
                    (4649, "WEFL - Western Flycatcher"),
                    (4680, "HAFL - Hammond's Flycatcher"),
                    (6320, "HUVI - Hutton's Vireo"),
                    (6292, "CAVI - Cassin's Vireo"),
                    (6270, "WAVI - Warbling Vireo"),
                    (4780, "STJA - Steller's Jay"),
                    (4880, "AMCR - American Crow"),
                    (4813, "CASJ - California Scrub-Jay"),
                    (4860, "CORA - Common Raven"),
                    (6110, "PUMA - Purple Martin"),
                    (6140, "TRES - Tree Swallow"),
                    (6150, "VGSW - Violet-green Swallow"),
                    (6120, "CLSW - Cliff Swallow"),
                    (6130, "BARS - Barn Swallow"),
                    (7350, "BCCH - Black-capped Chickadee"),
                    (7410, "CBCH - Chestnut-backed Chickadee"),
                    (7430, "BUSH - Bushtit"),
                    (7280, "RBNU - Red-breasted Nuthatch"),
                    (7260, "BRCR - Brown Creeper"),
                    (7210, "HOWR - House Wren"),
                    (7221, "PAWR - Pacific Wren"),
                    (7250, "MAWR - Marsh Wren"),
                    (7190, "BEWR - Bewick's Wren"),
                    (7480, "GCKI - Golden-crowned Kinglet"),
                    (7490, "RCKI - Ruby-crowned Kinglet"),
                    (7610, "AMRO - American Robin"),
                    (7590, "HETH - Hermit Thrush"),
                    (4930, "EUST - European Starling"),
                    (6190, "CEDW - Cedar Waxwing"),
                    (5190, "HOFI - House Finch"),
                    (5170, "PUFI - Purple Finch"),
                    (5210, "RECR - Red Crossbill"),
                    (5330, "PISI - Pine Siskin"),
                    (5290, "AMGO - American Goldfinch"),
                    (5140, "EVGR - Evening Grosbeak"),
                    (6800, "MGWA - MacGillivray's Warbler"),
                    (6810, "COYE - Common Yellowthroat"),
                    (6520, "YEWA - Yellow Warbler"),
                    (6560, "AUWA - Audubon's Warbler"),
                    (6650, "BTYW - Black-throated Gray Warbler"),
                    (6850, "WIWA - Wilson's Warbler"),
                    (5600, "CHSP - Chipping Sparrow"),
                    (5420, "SAVS - Savannah Sparrow"),
                    (5547, "PSWS - Puget Sound White-crowned Sparrow"),
                    (5540, "WCSP - White-crowned Sparrow"),
                    (5671, "ORJU - Oregon Junco"),
                    (6070, "WETA - Western Tanager"),
                    (5960, "BHGR - Black-headed Grosbeak"),
                    (4980, "RWBL - Red-winged Blackbird"),
                    (5100, "BRBL - Brewer's Blackbird"),
                    (4950, "BHCO - Brown-headed Cowbird"),
                    (3159, "ECDO - Eurasian Collared-Dove"),
                    (7670, "WEBL - Western Bluebird"),
                    (3790, "NOPO - Northern Pygmy-Owl"),
                    (5990, "LAZB - Lazuli Bunting"),
                ],
                default=5810,
                validators=[
                    django.core.validators.MinValueValidator(
                        1000, message="Species number must be at least 4 digits long."
                    ),
                    django.core.validators.MaxValueValidator(
                        9999, message="Species number must be less than 5 digits."
                    ),
                ],
            ),
        ),
    ]
