# Generated by Django 5.0.4 on 2024-07-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_capturerecord_capture_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="capture_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "(N) New Bird"),
                    ("R", "(R) Recaptured Bird"),
                    ("L", "(L) Lost Band"),
                    ("D", "(D) Destroyed Band (and or dead)"),
                    ("U", "(U) Unbanded Bird"),
                    ("C", "(C) Changed band"),
                    ("A", "(A) Added Band"),
                ],
                max_length=1,
            ),
        ),
    ]
