# Generated by Django 5.0.3 on 2024-03-25 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_remove_capturerecord_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="net",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Net must be at least 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        21, message="Net must be less than 22."
                    ),
                ]
            ),
        ),
    ]
