# Generated by Django 5.0.3 on 2024-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_alter_capturerecord_species_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="species_number",
            field=models.IntegerField(
                choices=[
                    (-25, "MOQU - Montezuma Quail"),
                    (-24, "NOBO - Northern Bobwhite"),
                    (-23, "GAQU - Gambel's Quail"),
                    (-22, "CAQU - California Quail"),
                    (-21, "SCQU - Scaled Quail"),
                    (-20, "WITU - Wild Turkey"),
                    (-19, "WITU - Wild Turkey"),
                    (-18, "LEPC - Lesser Prairie-Chicken"),
                    (-17, "GRPC - Greater Prairie-Chicken"),
                    (-16, "STGR - Sharp-tailed Grouse"),
                    (-15, "SOGR - Sooty Grouse"),
                    (-14, "DUGR - Dusky Grouse"),
                    (-13, "RUGR - Ruffed Grouse"),
                    (-12, "WTPT - White-tailed Ptarmigan"),
                    (-11, "ROPT - Rock Ptarmigan"),
                    (-10, "WIPT - Willow Ptarmigan"),
                    (-9, "SPGR - Spruce Grouse"),
                    (-8, "GRSG - Greater Sage-Grouse"),
                    (-7, "RUGR - Ruffed Grouse"),
                    (-6, "CPEA - Common Peafowl"),
                    (-5, "RNEP - Ring-necked Pheasant"),
                    (-4, "GRAP - Gray Partridge"),
                    (-3, "HISN - Himalayan Snowcock"),
                    (-2, "CHUK - Chukar"),
                    (-1, "PLCH - Plain Chachalaca"),
                    (1320, "MALL - Mallard"),
                    (1350, "GADW - Gadwall"),
                    (1440, "WODU - Wood Duck"),
                    (1720, "CANG - Canada Goose"),
                    (1900, "AMBI - American Bittern"),
                    (1940, "GBHE - Great Blue Heron"),
                    (2120, "VIRA - Virginia Rail"),
                    (2730, "KILL - Killdeer"),
                ],
                default=5810,
            ),
        ),
    ]
