# Generated by Django 5.0.3 on 2024-03-25 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0005_alter_capturerecord_net"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capturerecord",
            name="date_time",
        ),
        migrations.AddField(
            model_name="capturerecord",
            name="capture_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="capturerecord",
            name="hold_time",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minutes held in hand.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
