# Generated by Django 5.0.3 on 2024-03-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_remove_capturerecord_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capturerecord",
            name="release_time",
        ),
        migrations.AddField(
            model_name="capturerecord",
            name="hold_time",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Time in minutes between capture and release.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
