# Generated by Django 5.0.3 on 2024-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_remove_capturerecord_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturerecord",
            name="cloacal_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("U", "Unknown"),
                    ("X", "Not Attempted"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
