# Generated by Django 5.0.3 on 2024-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_remove_capturerecord_release_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="hold_time",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minutes held in hand.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
