# Generated by Django 5.0.3 on 2024-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_alter_capturerecord_is_validated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capturerecord",
            name="scribe",
        ),
        migrations.AddField(
            model_name="capturerecord",
            name="scribe_initials",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
