# Generated by Django 5.0.3 on 2024-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0009_remove_capturerecord_scribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="scribe_initials",
            field=models.CharField(max_length=3),
        ),
    ]
