# Description: Reference data for MAPS and USGS banding codes and descriptions

STATION_LOCATIONS: dict = {
    "MORS": {
        "name": "Morse Preserve MAPS",
        "code": "MORS",
        "BBL_location_id": 223665,
        "net_set": [15, 2, 3, 14, 5, 6, 10, 9, 8, 7, 20, 21],
    },
    "GHPR": {
        "name": "Glacial Heritage Preserve MAPS",
        "code": "GHPR",
        "BBL_location_id": 0,
        "net_set": [1, 2, 3, 4, 5, 6, 11, 12, 13, 14, 15, 16],
    },
}

SPECIES: dict = {
    -1: {
        "common_name": "Plain Chachalaca",
        "scientific_name": "Ortalis vetula",
        "alpha_code": "PLCH",
        "species_number": -1,
        "band_sizes": [],
        "wing_chord_range": (0, 0),
        "WRP_groups": [],
        "sexing_criteria": {},
        "pyle_second_edition_page": 0,
    },
    -2: {
        "common_name": "Chukar",
        "scientific_name": "Alectoris chukar",
        "alpha_code": "CHUK",
        "species_number": -2,
        "band_sizes": [],
        "wing_chord_range": (0, 0),
        "WRP_groups": [],
        "sexing_criteria": {},
        "pyle_second_edition_page": 0,
    },
    -3: {
        "common_name": "Himalayan Snowcock",
        "scientific_name": "Tetraogallus himalayensis",
        "alpha_code": "HISN",
        "species_number": -3,
        # ... additional properties ...
    },
    -4: {
        "common_name": "Gray Partridge",
        "scientific_name": "Perdix perdix",
        "alpha_code": "GRAP",
        "species_number": -4,
        # ... additional properties ...
    },
    -5: {
        "common_name": "Ring-necked Pheasant",
        "scientific_name": "Phasianus colchicus",
        "alpha_code": "RNEP",
        "species_number": -5,
        # ... additional properties ...
    },
    -6: {
        "common_name": "Common Peafowl",
        "scientific_name": "Pavo cristatus",
        "alpha_code": "CPEA",
        "species_number": -6,
        # ... additional properties ...
    },
    -7: {
        "common_name": "Ruffed Grouse",
        "scientific_name": "Bonasa umbellus",
        "alpha_code": "RUGR",
        "species_number": -7,
        # ... additional properties ...
    },
    -8: {
        "common_name": "Greater Sage-Grouse",
        "scientific_name": "Centrocercus urophasianus",
        "alpha_code": "GRSG",
        "species_number": -8,
        # ... additional properties ...
    },
    -9: {
        "common_name": "Spruce Grouse",
        "scientific_name": "Falcipennis canadensis",
        "alpha_code": "SPGR",
        "species_number": -9,
        # ... additional properties ...
    },
    -10: {
        "common_name": "Willow Ptarmigan",
        "scientific_name": "Lagopus lagopus",
        "alpha_code": "WIPT",
        "species_number": -10,
        # ... additional properties ...
    },
    -11: {
        "common_name": "Rock Ptarmigan",
        "scientific_name": "Lagopus muta",
        "alpha_code": "ROPT",
        "species_number": -11,
        # ... additional properties ...
    },
    -12: {
        "common_name": "White-tailed Ptarmigan",
        "scientific_name": "Lagopus leucura",
        "alpha_code": "WTPT",
        "species_number": -12,
        # ... additional properties ...
    },
    -13: {
        "common_name": "Ruffed Grouse",
        "scientific_name": "Bonasa umbellus",
        "alpha_code": "RUGR",
        "species_number": -13,
        # ... additional properties ...
    },
    -14: {
        "common_name": "Dusky Grouse",
        "scientific_name": "Dendragapus obscurus",
        "alpha_code": "DUGR",
        "species_number": -14,
        # ... additional properties ...
    },
    -15: {
        "common_name": "Sooty Grouse",
        "scientific_name": "Dendragapus fuliginosus",
        "alpha_code": "SOGR",
        "species_number": -15,
        # ... additional properties ...
    },
    -16: {
        "common_name": "Sharp-tailed Grouse",
        "scientific_name": "Tympanuchus phasianellus",
        "alpha_code": "STGR",
        "species_number": -16,
        # ... additional properties ...
    },
    -17: {
        "common_name": "Greater Prairie-Chicken",
        "scientific_name": "Tympanuchus cupido",
        "alpha_code": "GRPC",
        "species_number": -17,
        # ... additional properties ...
    },
    -18: {
        "common_name": "Lesser Prairie-Chicken",
        "scientific_name": "Tympanuchus pallidicinctus",
        "alpha_code": "LEPC",
        "species_number": -18,
        # ... additional properties ...
    },
    -19: {
        "common_name": "Wild Turkey",
        "scientific_name": "Meleagris gallopavo",
        "alpha_code": "WITU",
        "species_number": -19,
        # ... additional properties ...
    },
    -20: {
        "common_name": "Wild Turkey",
        "scientific_name": "Meleagris gallopavo",
        "alpha_code": "WITU",
        "species_number": -20,
        # ... additional properties ...
    },
    -21: {
        "common_name": "Scaled Quail",
        "scientific_name": "Callipepla squamata",
        "alpha_code": "SCQU",
        "species_number": -21,
        # ... additional properties ...
    },
    -22: {
        "common_name": "California Quail",
        "scientific_name": "Callipepla californica",
        "alpha_code": "CAQU",
        "species_number": -22,
        # ... additional properties ...
    },
    -23: {
        "common_name": "Gambel's Quail",
        "scientific_name": "Callipepla gambelii",
        "alpha_code": "GAQU",
        "species_number": -23,
        # ... additional properties ...
    },
    -24: {
        "common_name": "Northern Bobwhite",
        "scientific_name": "Colinus virginianus",
        "alpha_code": "NOBO",
        "species_number": -24,
        # ... additional properties ...
    },
    -25: {
        "common_name": "Montezuma Quail",
        "scientific_name": "Cyrtonyx montezumae",
        "alpha_code": "MOQU",
        "species_number": -25,
        # ... additional properties ...
    },
    5810: {
        "common_name": "Song Sparrow",
        "scientific_name": "Melospiza melodia",
        "alpha_code": "SOSP",
        "species_number": 5810,
        "band_sizes": ["1B"],
        "wing_chord_range": (50, 90),
        "WRP_groups": [3, 4],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 527,
    },
    6460: {
        "common_name": "Orange-crowned Warbler",
        "scientific_name": "Leiothlypis celata lutescens",
        "alpha_code": "OCWA",
        "species_number": 6460,
        "band_sizes": ["0", "0A"],
        "wing_chord_range": (51, 66),
        "wing_chord_range_by_sex:": {
            "female": (51, 59),
            "male": (55, 62),
        },
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 589,
    },
    5880: {
        "common_name": "Spotted Towhee",
        "scientific_name": "Pipilo maculatus oregonus",
        "alpha_code": "SPTO",
        "species_number": 5880,
        "band_sizes": ["1D", "1A", "2"],
        "wing_chord_range": (76, 95),
        "wing_chord_range_by_sex": {
            "female": (75, 86),
            "male": (78, 89),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 538,
    },
    7580: {
        "common_name": "Swainson's Thrush",
        "scientific_name": "Catharus ustulatus",
        "alpha_code": "SWTH",
        "species_number": 7580,
        "band_sizes": ["1B"],
        "wing_chord_range": (86, 107),
        "wing_chord_range_by_sex": {
            "female": (86, 103),
            "male": (90, 107),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 422,
    },
    4310: {
        "common_name": "Anna's Hummingbird",
        "scientific_name": "Calypte anna",
        "alpha_code": "ANHU",
        "species_number": 4310,
        "band_sizes": ["NONE"],
        "wing_chord_range": (46, 52),
        "WRP_groups": [3, 5, 6],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 104,
    },
    3160: {
        "common_name": "Mourning Dove",
        "scientific_name": "Zenaida macroura",
        "alpha_code": "MODO",
        "species_number": 3160,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    4240: {
        "common_name": "Vaux's Swift",
        "scientific_name": "Chaetura vauxi",
        "alpha_code": "VASW",
        "species_number": 4240,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    4330: {
        "common_name": "Rufous Hummingbird",
        "scientific_name": "Selasphorus rufus",
        "alpha_code": "RUHU",
        "species_number": 4330,
        "band_sizes": ["None"],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": None,
    },
    2120: {
        "common_name": "Virginia Rail",
        "scientific_name": "Rallus limicola",
        "alpha_code": "VIRA",
        "species_number": 2120,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    3320: {
        "common_name": "Sharp-shinned Hawk",
        "scientific_name": "Accipiter striatus",
        "alpha_code": "SSHA",
        "species_number": 3320,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    3330: {
        "common_name": "Cooper's Hawk",
        "scientific_name": "Accipiter cooperii",
        "alpha_code": "COHA",
        "species_number": 3330,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    3750: {
        "common_name": "Great Horned Owl",
        "scientific_name": "Bubo virginianus",
        "alpha_code": "GHOW",
        "species_number": 3750,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    3900: {
        "common_name": "Belted Kingfisher",
        "scientific_name": "Megaceryle alcyon",
        "alpha_code": "BEKI",
        "species_number": 3900,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": None,
    },
    4030: {
        "common_name": "Red-breasted Sapsucker",
        "scientific_name": "Sphyrapicus ruber",
        "alpha_code": "RBSA",
        "species_number": 4030,
        "band_sizes": ["1A", "1B", "1D"],
        "wing_chord_range": (114, 133),
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 189,
    },
    3940: {
        "common_name": "Downy Woodpecker",
        "scientific_name": "Dryobates pubescens",
        "alpha_code": "DOWO",
        "species_number": 3940,
        "band_sizes": ["1B"],
        "wing_chord_range": (85, 115),
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 192,
    },
    3930: {
        "common_name": "Hairy Woodpecker",
        "scientific_name": "Dryobates villosus",
        "alpha_code": "HAWO",
        "species_number": 3930,
        "band_sizes": ["1D", "2", "1A"],
        "wing_chord_range": (110, 132),
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 198,
    },
    4130: {
        "common_name": "Red-shafted Flicker",
        "scientific_name": "Colaptes auratus cafer",
        "alpha_code": "RSFL",
        "species_number": 4130,
        "band_sizes": ["3", "3B"],
        "wing_chord_range": (155, 176),
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 202,
    },
    4050: {
        "common_name": "Pileated Woodpecker",
        "scientific_name": "Dryocopus pileatus",
        "alpha_code": "PIWO",
        "species_number": 4050,
        "band_sizes": ["4", "3A"],
        "wing_chord_range": (200, 256),
        "wing_chord_range_by_sex": {
            "female": (200, 246),
            "male": (210, 256),
        },
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 206,
    },
    4590: {
        "common_name": "Olive-sided Flycatcher",
        "scientific_name": "Contopus cooperi",
        "alpha_code": "OSFL",
        "species_number": 4590,
        "band_sizes": ["1B", "1"],
        "wing_chord_range": (96, 114),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 255,
        "tail_length": (61, 79),
        "exp_culmen": (17.2, 19.7),
        "tarsus": (14.3, 15.7),
    },
    4620: {
        "common_name": "Western Wood-Pewee",
        "scientific_name": "Contopus sordidulus",
        "alpha_code": "WEWP",
        "species_number": 4620,
        "band_sizes": ["0A", "0", "1"],
        "wing_chord_range": (74, 92),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 257,
        "tail_length": (55, 73),
        "exp_culmen": (12.8, 16.2),
        "tarsus": (11.7, 14.6),
    },
    4660: {
        "common_name": "Willow Flycatcher",
        "scientific_name": "Empidonax traillii",
        "alpha_code": "WIFL",
        "species_number": 4660,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (61, 77),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 265,
    },
    4649: {
        "common_name": "Western Flycatcher",
        "scientific_name": "Empidonax difficilis",
        "alpha_code": "WEFL",
        "species_number": 4649,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (59, 75),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 275,
    },
    4680: {
        "common_name": "Hammond's Flycatcher",
        "scientific_name": "Empidonax hammondii",
        "alpha_code": "HAFL",
        "species_number": 4680,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (62, 75),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 270,
    },
    6320: {
        "common_name": "Hutton's Vireo",
        "scientific_name": "Vireo huttoni",
        "alpha_code": "HUVI",
        "species_number": 6320,
        "band_sizes": ["0"],
        "wing_chord_range": (54, 66),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 288,
    },
    6292: {
        "common_name": "Cassin's Vireo",
        "scientific_name": "Vireo cassinii",
        "alpha_code": "CAVI",
        "species_number": 6292,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (66, 78),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 291,
    },
    6270: {
        "common_name": "Warbling Vireo",
        "scientific_name": "Vireo gilvus",
        "alpha_code": "WAVI",
        "species_number": 6270,
        "band_sizes": ["0", "1"],
        "wing_chord_range": (62, 73),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 294,
    },
    4780: {
        "common_name": "Steller's Jay",
        "scientific_name": "Cyanocitta stelleri",
        "alpha_code": "STJA",
        "species_number": 4780,
        "band_sizes": ["3", "2", "3B"],
        "wing_chord_range": (130, 163),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 310,
    },
    4880: {
        "common_name": "American Crow",
        "scientific_name": "Corvus brachyrhynchos",
        "alpha_code": "AMCR",
        "species_number": 4880,
        "band_sizes": ["5", "5A", "4", "4A"],
        "wing_chord_range": (244, 341),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 319,
    },
    4813: {
        "common_name": "California Scrub-Jay",
        "scientific_name": "Aphelocoma californica",
        "alpha_code": "CASJ",
        "species_number": 4813,
        "band_sizes": ["3", "2", "2A"],
        "wing_chord_range": (109, 134),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 314,
    },
    4860: {
        "common_name": "Common Raven",
        "scientific_name": "Corvus corax",
        "alpha_code": "CORA",
        "species_number": 4860,
        "band_sizes": ["7A", "6", "7"],
        "wing_chord_range": (386, 480),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 323,
    },
    6110: {
        "common_name": "Purple Martin",
        "scientific_name": "Progne subis",
        "alpha_code": "PUMA",
        "species_number": 6110,
        "band_sizes": ["1D", "1A", "2"],
        "wing_chord_range": (131, 156),
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 347,
    },
    6140: {
        "common_name": "Tree Swallow",
        "scientific_name": "Tachycineta bicolor",
        "alpha_code": "TRES",
        "species_number": 6140,
        "band_sizes": ["1", "0", "1C"],
        "wing_chord_range": (107, 125),
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 343,
    },
    6150: {
        "common_name": "Violet-green Swallow",
        "scientific_name": "Tachycineta thalassina",
        "alpha_code": "VGSW",
        "species_number": 6150,
        "band_sizes": ["1", "0", "1C"],
        "wing_chord_range": (102, 119),
        "wing_chord_range_by_sex": {
            "female": (102, 112),
            "male": (108, 119),
        },
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 345,
    },
    6120: {
        "common_name": "Cliff Swallow",
        "scientific_name": "Petrochelidon pyrrhonota",
        "alpha_code": "CLSW",
        "species_number": 6120,
        "band_sizes": ["1", "1C"],
        "wing_chord_range": (94, 117),
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 351,
    },
    6130: {
        "common_name": "Barn Swallow",
        "scientific_name": "Hirundo rustica",
        "alpha_code": "BARS",
        "species_number": 6130,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (108, 123),
        "WRP_groups": [3, 4],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 349,
    },
    7350: {
        "common_name": "Black-capped Chickadee",
        "scientific_name": "Poecile atricapillus",
        "alpha_code": "BCCH",
        "species_number": 7350,
        "band_sizes": ["0", "0A"],
        "wing_chord_range": (57, 73),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 326,
    },
    7410: {
        "common_name": "Chestnut-backed Chickadee",
        "scientific_name": "Poecile rufescens",
        "alpha_code": "CBCH",
        "species_number": 7410,
        "band_sizes": ["0", "0A"],
        "wing_chord_range": (54, 66),
        "wing_chord_range_by_sex": {
            "female": (54, 63),
            "male": (57, 66),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 330,
    },
    7430: {
        "common_name": "Bushtit",
        "scientific_name": "Psaltriparus minimus",
        "alpha_code": "BUSH",
        "species_number": 7430,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (43, 52),
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 354,
    },
    7280: {
        "common_name": "Red-breasted Nuthatch",
        "scientific_name": "Sitta canadensis",
        "alpha_code": "RBNU",
        "species_number": 7280,
        "band_sizes": ["0", "1"],
        "wing_chord_range": (60, 73),
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 368,
    },
    7260: {
        "common_name": "Brown Creeper",
        "scientific_name": "Certhia americana",
        "alpha_code": "BRCR",
        "species_number": 7260,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (56, 69),
        "WRP_groups": [3, 4],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 373,
    },
    7210: {
        "common_name": "House Wren",
        "scientific_name": "Troglodytes aedon",
        "alpha_code": "HOWR",
        "species_number": 7210,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (46, 55),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 383,
    },
    7221: {
        "common_name": "Pacific Wren",
        "scientific_name": "Troglodytes pacificus",
        "alpha_code": "PAWR",
        "species_number": 7221,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (42, 56),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 385,
    },
    7250: {
        "common_name": "Marsh Wren",
        "scientific_name": "Cistothorus palustris",
        "alpha_code": "MAWR",
        "species_number": 7250,
        "band_sizes": ["1C", "1"],
        "wing_chord_range": (42, 55),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 389,
    },
    7190: {
        "common_name": "Bewick's Wren",
        "scientific_name": "Thryomanes bewickii",
        "alpha_code": "BEWR",
        "species_number": 7190,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (47, 60),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 392,
    },
    7480: {
        "common_name": "Golden-crowned Kinglet",
        "scientific_name": "Regulus satrapa",
        "alpha_code": "GCKI",
        "species_number": 7480,
        "band_sizes": ["0A"],
        "wing_chord_range": (49, 62),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 361,
    },
    7490: {
        "common_name": "Ruby-crowned Kinglet",
        "scientific_name": "Corthylio calendula",
        "alpha_code": "RCKI",
        "species_number": 7490,
        "band_sizes": ["0A"],
        "wing_chord_range": (49, 64),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 361,
    },
    7610: {
        "common_name": "American Robin",
        "scientific_name": "Turdus migratorius caurinus",
        "alpha_code": "AMRO",
        "species_number": 7610,
        "band_sizes": ["2"],
        "wing_chord_range": (115, 137),
        "wing_chord_range_by_sex": {
            "female": (115, 132),
            "male": (120, 137),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 427,
    },
    7590: {
        "common_name": "Hermit Thrush",
        "scientific_name": "Catharus guttatus guttatus",
        "alpha_code": "HETH",
        "species_number": 7590,
        "band_sizes": ["1B", "1"],
        "wing_chord_range": (79, 96),
        "wing_chord_range_by_sex": {
            "female": (79, 92),
            "male": (84, 96),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 423,
    },
    4930: {
        "common_name": "European Starling",
        "scientific_name": "Sturnus vulgaris",
        "alpha_code": "EUST",
        "species_number": 4930,
        "band_sizes": ["2", "3", "2A"],
        "wing_chord_range": (113, 135),
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 408,
    },
    6190: {
        "common_name": "Cedar Waxwing",
        "scientific_name": "Bombycilla cedrorum",
        "alpha_code": "CEDW",
        "species_number": 6190,
        "band_sizes": ["1A"],
        "wing_chord_range": (87, 100),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 363,
    },
    5190: {
        "common_name": "House Finch",
        "scientific_name": "Haemorhous mexicanus",
        "alpha_code": "HOFI",
        "species_number": 5190,
        "band_sizes": ["1B"],
        "wing_chord_range": (70, 83),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 545,
    },
    5170: {
        "common_name": "Purple Finch",
        "scientific_name": "Haemorhous purpureus",
        "alpha_code": "PUFI",
        "species_number": 5170,
        "band_sizes": ["1", "1B"],
        "wing_chord_range": (17, 86),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 456,
    },
    5210: {
        "common_name": "Red Crossbill",
        "scientific_name": "Loxia curvirostra",
        "alpha_code": "RECR",
        "species_number": 5210,
        "band_sizes": ["1B", "1A"],
        "wing_chord_range": (78, 105),
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 461,
    },
    5330: {
        "common_name": "Pine Siskin",
        "scientific_name": "Spinus pinus",
        "alpha_code": "PISI",
        "species_number": 5330,
        "band_sizes": ["0", "0A"],
        "wing_chord_range": (66, 77),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 464,
    },
    5290: {
        "common_name": "American Goldfinch",
        "scientific_name": "Spinus tristis",
        "alpha_code": "AMGO",
        "species_number": 5290,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (62, 76),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 469,
    },
    5140: {
        "common_name": "Evening Grosbeak",
        "scientific_name": "Coccothraustes vespertinus",
        "alpha_code": "EVGR",
        "species_number": 5140,
        "band_sizes": ["1A", "2", "1D"],
        "wing_chord_range": (100, 117),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 448,
    },
    6800: {
        "common_name": "MacGillivray's Warbler",
        "scientific_name": "Geothlypis tolmiei",
        "alpha_code": "MGWA",
        "species_number": 6800,
        "band_sizes": ["1", "0", "0A"],
        "wing_chord_range": (53, 64),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 599,
    },
    6810: {
        "common_name": "Common Yellowthroat",
        "scientific_name": "Geothlypis trichas",
        "alpha_code": "COYE",
        "species_number": 6810,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (47, 62),
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 603,
    },
    6520: {
        "common_name": "Yellow Warbler",
        "scientific_name": "Setophaga petechia",
        "alpha_code": "YEWA",
        "species_number": 6520,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (55, 66),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 622,
    },
    6560: {
        "common_name": "Audubon's Warbler",
        "scientific_name": "Setophaga coronata auduboni",
        "alpha_code": "AUWA",
        "species_number": 6560,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (68, 82),
        "wing_chord_range_by_age": {
            "female": (68, 79),
            "male": (71, 82),
        },
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 633,
    },
    6550: {
        "common_name": "Myrtle Warbler",
        "scientific_name": "Setophaga coronata coronata",
        "alpha_code": "MYWA",
        "species_number": 6560,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (68, 82),
        "wing_chord_range_by_age": {
            "female": (63, 75),
            "male": (67, 79),
        },
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 633,
    },
    6556: {
        "common_name": "Yellow-rumped Warbler",
        "scientific_name": "Setophaga coronata",
        "alpha_code": "MYWA",
        "species_number": 6560,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (63, 82),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 633,
    },
    6650: {
        "common_name": "Black-throated Gray Warbler",
        "scientific_name": "Setophaga nigrescens",
        "alpha_code": "BTYW",
        "species_number": 6650,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (56, 68),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 640,
    },
    6850: {
        "common_name": "Wilson's Warbler",
        "scientific_name": "Cardellina pusilla",
        "alpha_code": "WIWA",
        "species_number": 6850,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (48, 58),
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 652,
    },
    5600: {
        "common_name": "Chipping Sparrow",
        "scientific_name": "Spizella passerina",
        "alpha_code": "CHSP",
        "species_number": 5600,
        "band_sizes": ["0", "0A", "1"],
        "wing_chord_range": (62, 76),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 492,
    },
    5420: {
        "common_name": "Savannah Sparrow",
        "scientific_name": "Passerculus sandwichensis",
        "alpha_code": "SAVS",
        "species_number": 5420,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (59, 81),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 525,
    },
    5547: {
        "common_name": "Puget Sound White-crowned Sparrow",
        "scientific_name": "Zonotrichia leucophrys pugetensis",
        "alpha_code": "PSWS",
        "species_number": 5547,
        "band_sizes": ["1B"],
        "wing_chord_range": (63, 75),
        "wing_chord_range_by_sex": {
            "female": (63, 71),
            "male": (67, 75),
        },
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 508,
    },
    5550: {
        "common_name": "Gambel's White-crowned Sparrow",
        "scientific_name": "Zonotrichia leucophrys gambelii",
        "alpha_code": "GWCS",
        "species_number": 5550,
        "band_sizes": ["1B"],
        "wing_chord_range": (69, 84),
        "wing_chord_range_by_sex": {
            "female": (69, 79),
            "male": (74, 84),
        },
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 508,
    },
    5540: {
        "common_name": "White-crowned Sparrow",
        "scientific_name": "Zonotrichia leucophrys",
        "alpha_code": "WCSP",
        "species_number": 5540,
        "band_sizes": ["1B"],
        "wing_chord_range": (63, 84),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 508,
    },
    5671: {
        "common_name": "Oregon Junco",
        "scientific_name": "Junco hyemalis oreganus",
        "alpha_code": "ORJU",
        "species_number": 5671,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (69, 81),
        "wing_chord_range_by_sex": {
            "female": (69, 77),
            "male": (72, 81),
        },
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 504,
    },
    6070: {
        "common_name": "Western Tanager",
        "scientific_name": "Piranga ludoviciana",
        "alpha_code": "WETA",
        "species_number": 6070,
        "band_sizes": ["1B"],
        "wing_chord_range": (85, 99),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 662,
    },
    5960: {
        "common_name": "Black-headed Grosbeak",
        "scientific_name": "Pheucticus melanocephalus",
        "alpha_code": "BHGR",
        "species_number": 5960,
        "band_sizes": ["1A", "1D", "2"],
        "wing_chord_range": (88, 107),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 670,
    },
    4980: {
        "common_name": "Red-winged Blackbird",
        "scientific_name": "Agelaius phoeniceus",
        "alpha_code": "RWBL",
        "species_number": 4980,
        "band_sizes": ["1D", "1A", "2"],
        "band_sizes_by_sex": {
            "female": ["1A", "1D"],
            "male": ["2", "1D"],
        },
        "wing_chord_range": (98, 127),
        "wing_chord_range_by_sex": {
            "female": (98, 107),
            "male": (117, 127),
        },
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
            "wing_chord_by_sex": True,
        },
        "pyle_second_edition_page": 562,
    },
    5100: {
        "common_name": "Brewer's Blackbird",
        "scientific_name": "Euphagus cyanocephalus",
        "alpha_code": "BRBL",
        "species_number": 5100,
        "band_sizes": ["2", "1D"],
        "wing_chord_range": (108, 133),
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 570,
    },
    4950: {
        "common_name": "Brown-headed Cowbird",
        "scientific_name": "Molothrus ater",
        "alpha_code": "BHCO",
        "species_number": 4950,
        "band_sizes": ["1B", "1A", "1D", "2"],
        "band_sizes_by_sex": {
            "female": ["1B", "1A", "1D"],
            "male": ["1A", "1D", "2", "1B"],
        },
        "wing_chord_range": (85, 115),
        "wing_chord_range_by_sex": {
            "female": (85, 103),
            "male": (96, 115),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 569,
    },
    3159: {
        "common_name": "Eurasian Collared-Dove",
        "scientific_name": "Streptopelia decaocto",
        "alpha_code": "ECDO",
        "species_number": 3159,
        "band_sizes": ["4A", "4"],
        "wing_chord_range": (172, 188),
        "WRP_groups": [3, 4, 5],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": False,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 48,
    },
    7670: {
        "common_name": "Western Bluebird",
        "scientific_name": "Sialia mexicana",
        "alpha_code": "WEBL",
        "species_number": 7670,
        "band_sizes": ["1B"],
        "wing_chord_range": (97, 115),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 413,
    },
    3790: {
        "common_name": "Northern Pygmy-Owl",
        "scientific_name": "Glaucidium gnoma",
        "alpha_code": "NOPO",
        "species_number": 3790,
        "band_sizes": ["3", "3B", "3A", "4"],
        "wing_chord_range": (82, 105),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": False,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 142,
    },
    5990: {
        "common_name": "Lazuli Bunting",
        "scientific_name": "Passerina amoena",
        "alpha_code": "LAZB",
        "species_number": 5990,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (63, 76),
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 674,
    },
    1720: {
        "common_name": "Canada Goose",
        "scientific_name": "Branta canadensis",
        "alpha_code": "CANG",
        "species_number": 1720,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 0,
    },
    1440: {
        "common_name": "Wood Duck",
        "scientific_name": "Aix sponsa",
        "alpha_code": "WODU",
        "species_number": 1440,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 0,
    },
    1350: {
        "common_name": "Gadwall",
        "scientific_name": "Mareca strepera",
        "alpha_code": "GADW",
        "species_number": 1350,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 0,
    },
    1320: {
        "common_name": "Mallard",
        "scientific_name": "Anas platyrhynchos",
        "alpha_code": "MALL",
        "species_number": 1320,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 0,
    },
    3120: {
        "common_name": "Band-tailed Pigeon",
        "scientific_name": "Patagioenas fasciata",
        "alpha_code": "BTPI",
        "species_number": 3120,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    2730: {
        "common_name": "Killdeer",
        "scientific_name": "Charadrius vociferus",
        "alpha_code": "KILL",
        "species_number": 2730,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    1900: {
        "common_name": "American Bittern",
        "scientific_name": "Botaurus lentiginosus",
        "alpha_code": "AMBI",
        "species_number": 1900,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    1940: {
        "common_name": "Great Blue Heron",
        "scientific_name": "Ardea herodias",
        "alpha_code": "GBHE",
        "species_number": 1940,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    3250: {
        "common_name": "Turkey Vulture",
        "scientific_name": "Cathartes aura",
        "alpha_code": "TUVU",
        "species_number": 3250,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    3640: {
        "common_name": "Osprey",
        "scientific_name": "Pandion haliaetus",
        "alpha_code": "OSPR",
        "species_number": 3640,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    3520: {
        "common_name": "Bald Eagle",
        "scientific_name": "Haliaeetus leucocephalus",
        "alpha_code": "BAEA",
        "species_number": 3520,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    3370: {
        "common_name": "Red-tail Hawk",
        "scientific_name": "Buteo jamaicensis",
        "alpha_code": "RTHA",
        "species_number": 3370,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    3650: {
        "common_name": "Barn Owl",
        "scientific_name": "Tyto alba",
        "alpha_code": "BANO",
        "species_number": 3650,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    3600: {
        "common_name": "American Kestrel",
        "scientific_name": "Falco sparverius",
        "alpha_code": "AMKE",
        "species_number": 3600,
        "band_sizes": [],
        "wing_chord_range": (),
        "WRP_groups": [],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 0,
    },
    6240: {
        "common_name": "Red-eyed Vireo",
        "scientific_name": "Vireo olivaceus",
        "alpha_code": "REVI",
        "species_number": 6240,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (72, 85),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 296,
    },
    6170: {
        "common_name": "Northern Rough-winged Swallow",
        "scientific_name": "Stelgidopteryx serripennis",
        "alpha_code": "NRWS",
        "species_number": 6240,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (99, 116),
        "wing_chord_range_by_sex": {
            "female": (99, 111),
            "male": (103, 116),
        },
        "WRP_groups": [4],
        "sexing_criteria": {
            "female_by_BP": False,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 346,
    },
    5080: {
        "common_name": "Bullock's Oriole",
        "scientific_name": "Icterus bullockii",
        "alpha_code": "BUOR",
        "species_number": 5080,
        "band_sizes": ["1A", "1B", "1D"],
        "wing_chord_range": (85, 104),
        "wing_chord_range_by_sex": {
            "female": (85, 98),
            "male": (91, 104),
        },
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True,
        },
        "pyle_second_edition_page": 554,
    },
    4200: {
        "common_name": "Common Nighthawk",
        "scientific_name": "Chordeiles minor",
        "alpha_code": "CONI",
        "species_number": 4200,
        "band_sizes": ["1D", "2", "1A"],
        "wing_chord_range": (184, 209),
        "WRP_groups": [3, 5],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": False,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 73,
    },
    5570: {
        "common_name": "Golden-crowned Sparrow",
        "scientific_name": "Zonotrichia atricapilla",
        "alpha_code": "GCSP",
        "species_number": 5570,
        "band_sizes": ["1B", "1A"],
        "wing_chord_range": (71, 83),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False,
        },
        "pyle_second_edition_page": 510,
    },
    5850: {
        "common_name": "Fox Sparrow",
        "scientific_name": "Passerella iliaca",
        "alpha_code": "FOSP",
        "species_number": 5850,
        "band_sizes": ["1A", "1B"],
        "wing_chord_range": (73, 92),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False
        },
        "pyle_second_edition_page": 501,
    },
    7630: {
        "common_name": "Varied Thrush",
        "scientific_name": "Ixoreus naevius",
        "alpha_code": "VATH",
        "species_number": 5850,
        "band_sizes": ["2"],
        "wing_chord_range": (118, 134),
        "WRP_groups": [3],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True
        },
        "pyle_second_edition_page": 429,
    },
    6450: {
        "common_name": "Nashville Warbler",
        "scientific_name": "Leiothlypis ruficapilla",
        "alpha_code": "NAWA",
        "species_number": 6450,
        "band_sizes": ["0A", "0"],
        "wing_chord_range": (52, 64),
        "WRP_groups": [3, 8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": True
        },
        "pyle_second_edition_page": 594,
    },
    5830: {
        "common_name": "Lincoln's Sparrow",
        "scientific_name": "Melospiza lincolnii",
        "alpha_code": "LISP",
        "species_number": 5830,
        "band_sizes": ["1", "0"],
        "wing_chord_range": (54, 69),
        "WRP_groups": [8],
        "sexing_criteria": {
            "female_by_BP": True,
            "male_by_CP": True,
            "plumage_dimorphism": False
        },
        "pyle_second_edition_page": 531,
    },
}

WRP_GROUPS: dict = {
    3: {
        "description": (
            "Group 3 - Preformative molt less than complete, prebasic molt complete, "
            "and no prealternate molts occur."
        ),
        "codes_allowed": [
            "FPJ",
            "FCJ",
            "FPF",
            "FCF",
            "SPB",
            "DCB",
            "MFCF",
            "MSPB",
        ],
    },
    4: {
        "description": "Group 4 - Preformative and prebasic molts complete, and no prealternate molts occur.",
        "codes_allowed": [
            "FPJ",
            "FCJ",
            "FPF",
            "MFCF",
            "MSPB",
        ],
    },
    5: {
        "description": (
            "Group 5 - Preformative and prebasic molts less than complete and no prealternate molts occur."
        ),
        "codes_allowed": [
            "FPJ",
            "FCJ",
            "FPF",
            "FCF",
            "MFCF",
            "SPB",
            "MSPB",
            "SCB",
            "TPB",
            "DCB",
            "DPB",
            "TCB",
            "MTCB",
            "4PB",
        ],
    },
    6: {
        "description": (
            "Group 6 - Preformative molt less than complete, prebasic molt less than complete or "
            "complete. Prealternate molt occurs in the definitive but not the first cycle."
        ),
        "codes_allowed": [
            "FPJ",
            "FCJ",
            "FPF",
            "FCF",
            "SPB",
            "DPA",
            "DCA",
            "DPB",
            "DCB",
            "SCB",
            "SPA",
            "SCA",
            "TPB",
        ],
    },
    8: {
        "description": (
            "Group 8 - Preformative molt less than complete, prebasic molt complete, "
            "and prealternate molt occur in both first and definitive cycles."
        ),
        "codes_allowed": [
            "FPJ",
            "FCJ",
            "FPF",
            "FCF",
            "MFCF",
            "FPA",
            "MFPA",
            "FCA",
            "MFCA",
            "SPB",
            "MSPB",
            "DCB",
            "DPA",
            "DCA",
            "DPB",
            "DCU",
            "FCU",
        ],
    },
}

DISPOSTIONS: dict = {
    "N": {
        "maps": {
            "description": "New Bird",
            "code": "N",
        },
        "usgs": {
            "description": "Add (New Band)",
            "code": "1",
        },
    },
    "R": {
        "maps": {
            "description": "Recaptured Bird",
            "code": "R",
        },
        "usgs": {
            "description": "Added-To",
            "code": "6",
        },
    },
    "L": {
        "maps": {
            "description": "Lost Band",
            "code": "L",
        },
        "usgs": {
            "description": "Band Lost",
            "code": "8",
        },
    },
    "D": {
        "maps": {
            "description": "Destroyed Band (and or dead)",
            "code": "D",
        },
        "usgs": {
            "description": "Destroyed",
            "code": ["4", "X"],
        },
    },
    "U": {
        "maps": {
            "description": "Unbanded Bird",
            "code": "U",
        },
        "usgs": {
            "description": "Unbanded, not used",
            "code": "none",
        },
    },
    "C": {
        "maps": {
            "description": "Changed Band",
            "code": "C",
        },
        "usgs": {
            "description": "Replacing Band",
            "code": "5",
        },
    },
}

AGES_ANNUAL: dict = {
    4: {
        "maps": {
            "code": "4",
            "description": "Local (incapable of sustained flight)",
        },
        "usgs": {
            "code": "L",
            "description": "Local",
        },
        "allowed_wrp_codes": ["FPJ"],
    },
    2: {
        "maps": {
            "code": "2",
            "description": "Hatch Year (HY)",
        },
        "usgs": {
            "code": "HY",
            "description": "Hatching Year",
        },
        "allowed_wrp_codes": ["FPJ", "FCJ", "FPF", "FCF"],
    },
    1: {
        "maps": {
            "code": "1",
            "description": "After Hatch Year (AHY)",
        },
        "usgs": {
            "code": "AHY",
            "description": "After Hatching Year",
        },
        "allowed_wrp_codes": ["MFCF", "MFPA", "MFCA", "MSPB"],
    },
    5: {
        "maps": {
            "code": "5",
            "description": "Second Year (SY)",
        },
        "usgs": {
            "code": "SY",
            "description": "Second Year",
        },
        "allowed_wrp_codes": ["FCF", "FPA", "FCA", "FCU", "SPB"],
    },
    6: {
        "maps": {
            "code": "6",
            "description": "After Second Year (ASY)",
        },
        "usgs": {
            "code": "ASY",
            "description": "After Second Year",
        },
        "allowed_wrp_codes": ["DPA", "MDCA", "DCA", "DPB", "DCB", "DCU"],
    },
    7: {
        "maps": {
            "code": "7",
            "description": "Third Year (TY)",
        },
        "usgs": {
            "code": "TY",
            "description": "Third Year",
        },
        "allowed_wrp_codes": ["MSCB", "SCB", "DPA", "DCA", "MTCB", "TCB", "4PB"],
    },
    8: {
        "maps": {
            "code": "8",
            "description": "After Third Year (ATY)",
        },
        "usgs": {
            "code": "ATY",
            "description": "After Third Year",
        },
        "allowed_wrp_codes": ["DPB", "DCB", "DCU"],
    },
    0: {
        "maps": {
            "code": "0",
            "description": "Indeterminable Age",
        },
        "usgs": {
            "code": "U",
            "description": "Unknown",
        },
        "allowed_wrp_codes": ["UCU"],
    },
    9: {
        "maps": {
            "code": "9",
            "description": "Not attempted",
        },
        "usgs": {
            "code": "U",
            "description": "Unknown",  # Assuming 'U' is equivalent to 'Not attempted'
        },
        "allowed_wrp_codes": ["UCU"],
    },
}

AGES_WRP: dict = {
    "FPJ": {
        "description": "First prejuvenile molt",
        "detail": "(FPJ) First prejuvenile molt",
    },
    "FCJ": {
        "description": "First cycle juvenile plumage",
        "detail": "(FCJ) First cycle juvenile plumage",
    },
    "FPF": {
        "description": "First preformative molt",
        "detail": "(FPF) First preformative molt",
    },
    "FCF": {
        "description": "First cycle formative plumage",
        "detail": "(FCF) First cycle formative plumage",
    },
    "MFCF": {
        "description": "Minimum first cycle formative",
        "detail": "(M-FCF) Minimum first cycle formative",
    },
    "FPA": {
        "description": "First prealternate molt",
        "detail": "(FPA) First prealternate molt",
    },
    "MFPA": {
        "description": "Minimum first cycle prealternate",
        "detail": "(M-FPA) Minimum first cycle prealternate",
    },
    "FCA": {
        "description": "First cycle alternate plumage",
        "detail": "(FCA) First cycle alternate plumage",
    },
    "MFCA": {
        "description": "Minimum first cycle alternate",
        "detail": "(M-FCA) Minimum first cycle alternate",
    },
    "SPB": {
        "description": "Second prebasic molt",
        "detail": "(SPB) Second prebasic molt",
    },
    "MSPB": {
        "description": "Minimum second prebasic molt",
        "detail": "(M-SPB) Minimum second prebasic molt",
    },
    "SCB": {
        "description": "Second cycle basic plumage",
        "detail": "(SCB) Second cycle basic plumage",
    },
    "DPB": {
        "description": "Definitive prebasic molt",
        "detail": "(DPB) Definitive prebasic molt",
    },
    "DCB": {
        "description": "Definitive cycle basic plumage",
        "detail": "(DCB) Definitive cycle basic plumage",
    },
    "DPA": {
        "description": "Definitive prealternate molt",
        "detail": "(DPA) Definitive prealternate molt",
    },
    "DCA": {
        "description": "Definitive cycle alternate plumage",
        "detail": "(DCA) Definitive cycle alternate plumage",
    },
    "TPB": {
        "description": "Third prebasic molt",
        "detail": "(TPB) Third prebasic molt",
    },
    "FCU": {
        "description": "First cycle unknown plumage",
        "detail": "(FCU) First cycle unknown plumage",
    },
    "DCU": {
        "description": "Definitive cycle unknown plumage",
        "detail": "(DCU) Definitive cycle unknown plumage",
    },
    "UCU": {
        "description": "Unknown cycle unknown plumage",
        "detail": "(UCU) Unknown cycle unknown plumage",
    },
}

HOW_AGE_DETERMINED: dict = {
    "S": {
        "maps": {
            "code": "S",
            "description": "Skull",
        },
        "usgs": {
            "code": "SK",
            "description": "Skull",
        },
    },
    "C": {
        "maps": {
            "code": "C",
            "description": "Cloacal Protuberance",
        },
        "usgs": {
            "code": "CL",
            "description": "Cloacal Protuberance",
        },
    },
    "B": {
        "maps": {
            "code": "B",
            "description": "Brood Patch",
        },
        "usgs": {
            "code": "BP",
            "description": "Brood Patch",
        },
    },
    "F": {
        "maps": {
            "code": "F",
            "description": "Feather Wear",
        },
        "usgs": {
            "code": "FF",
            "description": "Flight feathers (remiges), condition or color",
        },
    },
    "J": {
        "maps": {
            "code": "J",
            "description": "Juvenile Body Plumage",
        },
        "usgs": {
            "code": "PL",
            "description": "Body Plumage",
        },
    },
    "M": {
        "maps": {
            "code": "M",
            "description": "Molt",
        },
        "usgs": {
            "code": "MR",
            "description": "Flight feathers (remiges), condition or color",
        },
    },
    "P": {
        "maps": {
            "code": "P",
            "description": "Plumage (non-juvenile)",
        },
        "usgs": {
            "code": "PL",
            "description": "Body Plumage",
        },
    },
    "N": {
        "maps": {
            "code": "N",
            "description": "Non-feather",
        },
    },
    "L": {
        "maps": {
            "code": "L",
            "description": "Molt Limit",
        },
        "usgs": {
            "code": "LP",
            "description": "Molt limit present",
        },
    },
    "I": {
        "maps": {
            "code": "I",
            "description": "Mouth/Bill",
        },
        "usgs": {
            "code": "MB",
            "description": "Mouth/Bill",
        },
    },
    "E": {
        "maps": {
            "code": "E",
            "description": "Eye color",
        },
        "usgs": {
            "code": "EY",
            "description": "Eye color",
        },
    },
    "W": {
        "maps": {
            "code": "W",
            "description": "Wing length",
        },
    },
    "T": {
        "maps": {
            "code": "T",
            "description": "Tail length",
        },
    },
    "O": {
        "maps": {
            "code": "O",
            "description": "Other (specify in notes)",
        },
        "usgs": {
            "code": "OT",
            "description": "Other",
        },
    },
}

SEXES: dict = {
    "M": {
        "maps": {
            "code": "M",
            "description": "Male",
        },
        "usgs": {
            "code": "M",
            "description": "Male",
        },
    },
    "F": {
        "maps": {
            "code": "F",
            "description": "Female",
        },
        "usgs": {
            "code": "F",
            "description": "Female",
        },
    },
    "U": {
        "maps": {
            "code": "U",
            "description": "Unknown",
        },
        "usgs": {
            "code": "U",
            "description": "Unknown",
        },
    },
    "X": {
        "maps": {
            "code": "X",
            "description": "Not Attempted",
        },
        "usgs": {
            "code": "U",
            "description": "Unknown",
        },
    },
}

BREEDING_STATUSES: dict = {
    "Cn": {
        "code": "Cn",
        "description": "Confirmed Breeder. Carrying Nesting Material",
        "rank": 11,
    },
    "Cm": {
        "code": "Cm",
        "description": "Confirmed Breeder. Carrying nest material",
        "rank": 10,
    },
    "Cf": {
        "code": "Cf",
        "description": "Confirmed Breeder. Carrying food or fecal sac",
        "rank": 9,
    },
    "Cd": {
        "code": "Cd",
        "description": "Confirmed Breeder. Distraction Display",
        "rank": 8,
    },
    "Cl": {
        "code": "Cl",
        "description": "Confirmed Breeder. Local bird",
        "rank": 7,
    },
    "Pc": {
        "code": "Pc",
        "description": "Probable Breeder. Courtship/copulation",
        "rank": 6,
    },
    "Pt": {
        "code": "Pt",
        "description": "Probable Breeder. Other territorial behavior",
        "rank": 5,
    },
    "Ps": {
        "code": "Ps",
        "description": "Probable Breeder. Song/drumming",
        "rank": 4,
    },
    "Ob": {
        "code": "Ob",
        "description": "Observed. Banded/Captured",
        "rank": 3,
    },
    "Oe": {
        "code": "Oe",
        "description": "Observed. Encountered",
        "rank": 2,
    },
    "Oo": {
        "code": "Oo",
        "description": "Observed. Flyover",
        "rank": 1,
    },
    "--": {
        "code": "--",
        "description": "Absent",
        "rank": 0,
    },
}
