from django.db import models
from common.models import BaseModel

# Create your models here.
class CaptureRecord(BaseModel): 
    bander_initials = models.CharField(max_length=3)
    record_code = models.CharField(max_length=1)
    band_number = models.IntegerField()
    species_name = models.CharField(max_length=50)
    alpha_code = models.CharField(max_length=4)
    age_annual = models.CharField(max_length=1)
    how_aged_1 = models.CharField(max_length=1)
    how_aged_2 = models.CharField(max_length=1)
    age_WRP = models.CharField(max_length=4)
    sex = models.CharField(max_length=1)
    how_sexed_1 = models.CharField(max_length=1)
    how_sexed_2 = models.CharField(max_length=1)
    skull = models.IntegerField(max_length=1)
    cloacal_protuberance = models.IntegerField(max_length=1)
    brood_patch = models.IntegerField(max_length=1)
    fat = models.IntegerField(max_length=1)
    body_molt = models.IntegerField(max_length=1)
    ff_molt = models.CharField(max_length=1)
    ff_wear = models.IntegerField(max_length=1)
    juv_body_plumage = models.IntegerField(max_length=1)
    primary_coverts = models.CharField(max_length=1)
    secondary_coverts = models.CharField(max_length=1)
    primaries = models.CharField(max_length=1)
    rectrices = models.CharField(max_length=1)
    secondaries = models.CharField(max_length=1)
    tertials = models.CharField(max_length=1)
    body_plumage = models.CharField(max_length=1)
    non_feather = models.CharField(max_length=1)
    wing_chord = models.IntegerField()
    body_mass = models.DecimalField()
    status = models.IntegerField(max_length=3)
    date_time = models.DateTimeField()
    station = models.CharField(max_length=4)
    net = models.CharField(max_length=4)
    disposition = models.CharField(max_length=1)
    note_number = models.IntegerField()
    note = models.TextField()
    band_size = models.CharField(max_length=2)
    scribe = models.CharField(max_length=3)
    location = models.CharField(max_length=4)
