# Generated by Django 5.0.4 on 2024-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
