# Generated by Django 5.0.4 on 2024-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birds", "0002_alter_band_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agewrp",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="A longer explanation of the WRP group code, its meaning, and examples.",
                null=True,
            ),
        ),
    ]
