# Generated by Django 5.0.4 on 2024-04-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birds", "0004_alter_band_options_taxon_alpha_taxon_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandallocation",
            name="sex",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("u", "Unisex")],
                default="u",
                max_length=10,
            ),
        ),
    ]
