# Generated by Django 5.0.4 on 2024-05-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birds", "0005_alter_bandallocation_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="tail_female_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="tail_female_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="tail_male_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="tail_male_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="tail_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="tail_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
